language: go

go:
  - "1.14"

# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
branches:
  only:
    - master

install:
  # 安装最新的hugo
  - go get github.com/spf13/hugo 

script:
  # 运行hugo命令
  - hugo